---
- hosts: cassandras
  remote_user: root
  become: yes
  vars:
    cluster_name: cass_cluster
    seeds: "{{ hostvars[groups['cassandras'][0]].inventory_hostname }}"
  roles:
    - java
    - cassandra
