---
# - name: debug
#   ansible.builtin.debug:
#     msg: "{{ hostvars[inventory_hostname].ansible_host }}"

- name: create Cassandra folder
  file:
    path: /cassandra
    state: directory
    mode: 0777

- name: copy and extract Cassandra file
  unarchive:
    src: apache-cassandra-2.2.12-bin.tar.gz
    dest: /cassandra

- name: override cassandra.yaml
  template:
    src: cassandra.yaml
    dest: /cassandra/apache-cassandra-2.2.12/conf

- name: start Cassandra seed
  shell: "/cassandra/apache-cassandra-2.2.12/bin/cassandra -d"
  async: 1
  poll: 0
  when: inventory_hostname == seeds

- name: wait Cassandra up and running
  wait_for:
    port: 9042
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    delay: 10
    timeout: 60
  when: inventory_hostname == seeds
  connection: local

- name: start Cassandra node
  shell: "/cassandra/apache-cassandra-2.2.12/bin/cassandra -d"
  async: 1
  poll: 0
  when: inventory_hostname != seeds

- name: wait Cassandra up and running
  wait_for:
    port: 9042
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    delay: 10
    timeout: 120
  when: inventory_hostname != seeds
  connection: local
